version: '3'
services:
  caddy:
    build:
      context: ${CADDY_IMAGE_PATH}
    volumes:
      - /mnt:/mnt
      - ${APP_CODE_PATH_HOST}:/var/www:cached
      - ${CADDY_IMAGE_PATH}/config/Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_VHOSTS_FILE}:/etc/caddy/vhosts
      - ${CADDY_HOST_LOG_PATH}:/var/log/caddy
      - ${DATA_PATH_HOST}:/root/.caddy
    ports:
      - "${CADDY_HOST_HTTP_PORT}:80"
      - "${CADDY_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
