version: '3'
services:
  php-fpm:
    build:
      context: ${PHP_IMAGE_PATH}
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www:cached
      - ${PHP_IMAGE_PATH}/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    depends_on:
      - workspace
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - backend
